stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  CI: ""

build:
  stage: build
  image: node:11
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - npm run build

deploy:
  stage: deploy
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=frontend-assignment1-danielasa --api-key=$HEROKU_API_KEY --skip_cleanup
  environment:
    name: staging
    url: https://frontend-assignment1-danielasa.herokuapp.com/
  only:
    - production
